### ISSUE TITLE
missing indigogroupbox

### ISSUE THREAD

**Issue by aoloe** [nitramr/indigoDock#11]
i could not compile the newest commits...

indigopanel.cpp:5:28: fatal error: indigogroupbox.h: No such file or directory

**Comment by nitramr** [comment]
It's fixed now... There was an obsolete include.

**Comment by luzpaz** [comment]
I get this result on OSX 10.10.5 Qt Creator 3.5.1 (opensource) Based on Qt 5.5.1 (Clang 6.1 (Apple), 64 bit)
![screenshot 2015-11-15 11 09 33](https://cloud.githubusercontent.com/assets/4140247/11169863/6222836a-8b89-11e5-8f23-655afb3b2448.png)

**Comment by aoloe** [comment]
i also don't get the icons...

i've spent a few hours and try to understand how resources work, but i jsut get a missing pixmap error...

**Comment by nitramr** [comment]
Mh... I don't know if the resources working in another way as on linux (it's also an unix system). Maybe the reason is the access right for the image files?

In the code the image path is like this:
QIcon(":/icons/icons/placeholder.png") <- its only a reference to the resource file.

Furthermore I see in the screenshot also the missing close button on IndigoPanel. The difference here is I used a standard icon from Qt, like this:
m_btnClose->setIcon(style()->standardIcon(QStyle::SP_TitleBarCloseButton));

It's included in the "Tabbar mouse wheel fix" commitment

**Comment by aoloe** [comment]
... i'm using linux... :-) no icons, either...

how are you running the project?

```
qmake
make
./TestLayout
```

?

**Comment by nitramr** [comment]
I use Qt 5.5.0 GCC 64bit, compiler is qmake. I run the project via execute button in Qt (Strg+R)

**Comment by nitramr** [comment]
I found the reason... the resource file has a language setting... I have used the standard for me (de). If I change it to (en) I see no images.

![auswahl_007](https://cloud.githubusercontent.com/assets/15112256/11195057/0b9725c8-8cb0-11e5-81b7-e5b3c2912ce1.png)

**Comment by nitramr** [comment]
I have removed the language setting in my last commit (colorswatch added...). Now it should work

**Comment by luzpaz** [comment]
I tested https://github.com/nitramr/indigoDock/commit/4a58403605b8c9e4621d30d9e8db77e5c23d0c88 and here is how it looks on MacOSX. As you can see, some icons are visible. 
Issues:  
- Icon tabs are centered vertically

![screenshot 2015-11-16 15 42 42](https://cloud.githubusercontent.com/assets/4140247/11195761/4458c8da-8c79-11e5-9f96-59004da4680e.png)

**Comment by aoloe** [comment]
yep, i get the icons now!
thanks.

**Comment by luzpaz** [comment]
We can close this issue now
